common:
  exp:
    use_amp: false
    debug: false
    dont_use_env: true
    exp_root_path: ./output/predictors/latency/segmentation/dynamic/without-grid
    resume: false
    seed: 42
    deterministic: false
    validation_frequency: 5
  supernet_config:
    type: CompositeSuperNet
    backbone:
      type: OFAMobileNet
      ks_list:
      - 3
      - 5
      depth_list:
      - 2
      - 3
      - 4
      expand_ratio_list:
      - 3
      - 4
      - 6
      width_mult_list:
      - 1.0
      bn_eps: 1.0e-05
      bn_momentum: 0.1
      catch_counter: 5
    neck:
      type: DynamicFPN
      levels: 5
      mid_channels: 128
      convs:
      - [[96, 3]]
      - [[136, 3]]
      - [[176, 3]]
      - [[216, 3]]
      - [[256, 3]]
      merge_policy: sum
      act_func: relu
      use_bias: false
      upsample_mode: nearest
    head:
      type: SegmentationHead
      levels: 5
      in_channels:
      - 96
      - 136
      - 176
      - 216
      - 256
      mid_channels: 128
      n_classes: 12
      use_bias: false
      upsample_mode: nearest
      upsample_factor: 2
      final_conv_kernel: 3
      merge_policy: sum
stages:
  lat_pred_learn:
    stage_type: PredictorLearn
    pred_learn:
      metric: latency
      model: Perceptron
      n_epochs: 200
      init_lr: 0.003
      data_path: performance_dataset/nvidia/dynamic-fpn/without-grid/segmentation_latency.json
      image_size_list: [[384, 480]]
execute:
- lat_pred_learn
